# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PortalAdministrativo_pb2 as PortalAdministrativo__pb2


class PortalAdministrativoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NovoAluno = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/NovoAluno',
                request_serializer=PortalAdministrativo__pb2.Aluno.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Status.FromString,
                )
        self.EditaAluno = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/EditaAluno',
                request_serializer=PortalAdministrativo__pb2.Aluno.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Status.FromString,
                )
        self.RemoveAluno = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/RemoveAluno',
                request_serializer=PortalAdministrativo__pb2.Identificador.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Status.FromString,
                )
        self.ObtemAluno = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/ObtemAluno',
                request_serializer=PortalAdministrativo__pb2.Identificador.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Aluno.FromString,
                )
        self.ObtemTodosAlunos = channel.unary_stream(
                '/projectCadastro.PortalAdministrativo/ObtemTodosAlunos',
                request_serializer=PortalAdministrativo__pb2.Vazia.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Aluno.FromString,
                )
        self.NovoProfessor = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/NovoProfessor',
                request_serializer=PortalAdministrativo__pb2.Professor.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Status.FromString,
                )
        self.EditaProfessor = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/EditaProfessor',
                request_serializer=PortalAdministrativo__pb2.Professor.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Status.FromString,
                )
        self.RemoveProfessor = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/RemoveProfessor',
                request_serializer=PortalAdministrativo__pb2.Identificador.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Status.FromString,
                )
        self.ObtemProfessor = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/ObtemProfessor',
                request_serializer=PortalAdministrativo__pb2.Identificador.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Professor.FromString,
                )
        self.ObtemTodosProfessores = channel.unary_stream(
                '/projectCadastro.PortalAdministrativo/ObtemTodosProfessores',
                request_serializer=PortalAdministrativo__pb2.Vazia.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Professor.FromString,
                )
        self.NovaDisciplina = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/NovaDisciplina',
                request_serializer=PortalAdministrativo__pb2.Disciplina.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Status.FromString,
                )
        self.EditaDisciplina = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/EditaDisciplina',
                request_serializer=PortalAdministrativo__pb2.Disciplina.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Status.FromString,
                )
        self.RemoveDisciplina = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/RemoveDisciplina',
                request_serializer=PortalAdministrativo__pb2.Identificador.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Status.FromString,
                )
        self.ObtemDisciplina = channel.unary_unary(
                '/projectCadastro.PortalAdministrativo/ObtemDisciplina',
                request_serializer=PortalAdministrativo__pb2.Identificador.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Disciplina.FromString,
                )
        self.ObtemTodasDisciplinas = channel.unary_stream(
                '/projectCadastro.PortalAdministrativo/ObtemTodasDisciplinas',
                request_serializer=PortalAdministrativo__pb2.Vazia.SerializeToString,
                response_deserializer=PortalAdministrativo__pb2.Disciplina.FromString,
                )


class PortalAdministrativoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NovoAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditaAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemTodosAlunos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NovoProfessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditaProfessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProfessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemProfessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemTodosProfessores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NovaDisciplina(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditaDisciplina(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDisciplina(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemDisciplina(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtemTodasDisciplinas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortalAdministrativoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NovoAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.NovoAluno,
                    request_deserializer=PortalAdministrativo__pb2.Aluno.FromString,
                    response_serializer=PortalAdministrativo__pb2.Status.SerializeToString,
            ),
            'EditaAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.EditaAluno,
                    request_deserializer=PortalAdministrativo__pb2.Aluno.FromString,
                    response_serializer=PortalAdministrativo__pb2.Status.SerializeToString,
            ),
            'RemoveAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAluno,
                    request_deserializer=PortalAdministrativo__pb2.Identificador.FromString,
                    response_serializer=PortalAdministrativo__pb2.Status.SerializeToString,
            ),
            'ObtemAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtemAluno,
                    request_deserializer=PortalAdministrativo__pb2.Identificador.FromString,
                    response_serializer=PortalAdministrativo__pb2.Aluno.SerializeToString,
            ),
            'ObtemTodosAlunos': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtemTodosAlunos,
                    request_deserializer=PortalAdministrativo__pb2.Vazia.FromString,
                    response_serializer=PortalAdministrativo__pb2.Aluno.SerializeToString,
            ),
            'NovoProfessor': grpc.unary_unary_rpc_method_handler(
                    servicer.NovoProfessor,
                    request_deserializer=PortalAdministrativo__pb2.Professor.FromString,
                    response_serializer=PortalAdministrativo__pb2.Status.SerializeToString,
            ),
            'EditaProfessor': grpc.unary_unary_rpc_method_handler(
                    servicer.EditaProfessor,
                    request_deserializer=PortalAdministrativo__pb2.Professor.FromString,
                    response_serializer=PortalAdministrativo__pb2.Status.SerializeToString,
            ),
            'RemoveProfessor': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProfessor,
                    request_deserializer=PortalAdministrativo__pb2.Identificador.FromString,
                    response_serializer=PortalAdministrativo__pb2.Status.SerializeToString,
            ),
            'ObtemProfessor': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtemProfessor,
                    request_deserializer=PortalAdministrativo__pb2.Identificador.FromString,
                    response_serializer=PortalAdministrativo__pb2.Professor.SerializeToString,
            ),
            'ObtemTodosProfessores': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtemTodosProfessores,
                    request_deserializer=PortalAdministrativo__pb2.Vazia.FromString,
                    response_serializer=PortalAdministrativo__pb2.Professor.SerializeToString,
            ),
            'NovaDisciplina': grpc.unary_unary_rpc_method_handler(
                    servicer.NovaDisciplina,
                    request_deserializer=PortalAdministrativo__pb2.Disciplina.FromString,
                    response_serializer=PortalAdministrativo__pb2.Status.SerializeToString,
            ),
            'EditaDisciplina': grpc.unary_unary_rpc_method_handler(
                    servicer.EditaDisciplina,
                    request_deserializer=PortalAdministrativo__pb2.Disciplina.FromString,
                    response_serializer=PortalAdministrativo__pb2.Status.SerializeToString,
            ),
            'RemoveDisciplina': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDisciplina,
                    request_deserializer=PortalAdministrativo__pb2.Identificador.FromString,
                    response_serializer=PortalAdministrativo__pb2.Status.SerializeToString,
            ),
            'ObtemDisciplina': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtemDisciplina,
                    request_deserializer=PortalAdministrativo__pb2.Identificador.FromString,
                    response_serializer=PortalAdministrativo__pb2.Disciplina.SerializeToString,
            ),
            'ObtemTodasDisciplinas': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtemTodasDisciplinas,
                    request_deserializer=PortalAdministrativo__pb2.Vazia.FromString,
                    response_serializer=PortalAdministrativo__pb2.Disciplina.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'projectCadastro.PortalAdministrativo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PortalAdministrativo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NovoAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/NovoAluno',
            PortalAdministrativo__pb2.Aluno.SerializeToString,
            PortalAdministrativo__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditaAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/EditaAluno',
            PortalAdministrativo__pb2.Aluno.SerializeToString,
            PortalAdministrativo__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/RemoveAluno',
            PortalAdministrativo__pb2.Identificador.SerializeToString,
            PortalAdministrativo__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtemAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/ObtemAluno',
            PortalAdministrativo__pb2.Identificador.SerializeToString,
            PortalAdministrativo__pb2.Aluno.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtemTodosAlunos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/projectCadastro.PortalAdministrativo/ObtemTodosAlunos',
            PortalAdministrativo__pb2.Vazia.SerializeToString,
            PortalAdministrativo__pb2.Aluno.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NovoProfessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/NovoProfessor',
            PortalAdministrativo__pb2.Professor.SerializeToString,
            PortalAdministrativo__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditaProfessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/EditaProfessor',
            PortalAdministrativo__pb2.Professor.SerializeToString,
            PortalAdministrativo__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveProfessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/RemoveProfessor',
            PortalAdministrativo__pb2.Identificador.SerializeToString,
            PortalAdministrativo__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtemProfessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/ObtemProfessor',
            PortalAdministrativo__pb2.Identificador.SerializeToString,
            PortalAdministrativo__pb2.Professor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtemTodosProfessores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/projectCadastro.PortalAdministrativo/ObtemTodosProfessores',
            PortalAdministrativo__pb2.Vazia.SerializeToString,
            PortalAdministrativo__pb2.Professor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NovaDisciplina(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/NovaDisciplina',
            PortalAdministrativo__pb2.Disciplina.SerializeToString,
            PortalAdministrativo__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditaDisciplina(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/EditaDisciplina',
            PortalAdministrativo__pb2.Disciplina.SerializeToString,
            PortalAdministrativo__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveDisciplina(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/RemoveDisciplina',
            PortalAdministrativo__pb2.Identificador.SerializeToString,
            PortalAdministrativo__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtemDisciplina(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projectCadastro.PortalAdministrativo/ObtemDisciplina',
            PortalAdministrativo__pb2.Identificador.SerializeToString,
            PortalAdministrativo__pb2.Disciplina.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtemTodasDisciplinas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/projectCadastro.PortalAdministrativo/ObtemTodasDisciplinas',
            PortalAdministrativo__pb2.Vazia.SerializeToString,
            PortalAdministrativo__pb2.Disciplina.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
