import clienteMatricula
import servidorMatricula
import clienteAdministrativo
import servidorAdministrativo

import threading
from time import sleep

server_adm1 = threading.Thread(target=servidorAdministrativo.run_server, args=(50051,))
server_adm2 = threading.Thread(target=servidorAdministrativo.run_server, args=(50052,))

clienteAdministrativo1 = clienteAdministrativo.PortalAdministrativoCliente(50051)
clienteAdministrativo1_1 = clienteAdministrativo.PortalAdministrativoCliente(50051)
clienteAdministrativo2 = clienteAdministrativo.PortalAdministrativoCliente(50052)

server_mat1 = threading.Thread(target=servidorMatricula.run_server, args=(60061,))
server_mat2 = threading.Thread(target=servidorMatricula.run_server, args=(60062,))

clienteMatricula1 = clienteMatricula.PortalMatriculaCliente(60061)
clienteMatricula1_1 = clienteMatricula.PortalMatriculaCliente(60061)
clienteMatricula2 = clienteMatricula.PortalMatriculaCliente(60062)

server_adm1.start()
server_adm2.start()
server_mat1.start()
server_mat2.start()

# Falhas clienteAdministrativo
clienteAdministrativo1.editaAluno('12345', 'rafael')
sleep(2)
clienteAdministrativo2.removeAluno('123456')
sleep(2)
clienteAdministrativo1_1.removeProfessor('asdas09')
sleep(2)
clienteAdministrativo2.editaProfessor('asjh7', 'Carlinhos')
sleep(2)
clienteAdministrativo1.editaDisciplina('gbc011', 'matematica', 20)
sleep(2)
clienteAdministrativo2.removeDisciplina('gbc012')
sleep(2)

# Falhas clienteMatricula
clienteMatricula2.adicionaProfessor('gbc011', '09876')
sleep(2)
clienteMatricula1_1.removeProfessor('gbc011', '09876')
sleep(2)
clienteMatricula1.adicionaAluno('gbc011', '12345')
sleep(2)
clienteMatricula1.removeProfessor('gbc011', '09876')
sleep(2)
clienteMatricula2.detalheDisciplina('gbc011')
sleep(2)
clienteMatricula1.obtemDisciplinasAluno('12345')
sleep(2)
clienteMatricula1_1.obtemDisciplinasProfessor('09876')

# Sucesso no clienteAdministrativo
clienteAdministrativo1_1.novoAluno('12345', 'rafael')
sleep(2)
clienteAdministrativo2.obtemAluno('12345')
sleep(2)
clienteAdministrativo2.novoProfessor('09876', 'Carlinhos')
sleep(2)
clienteAdministrativo1_1.editaProfessor('09876', 'Victoria')
sleep(2)
clienteAdministrativo1.obtemTodosProfessores()
sleep(2)
clienteAdministrativo1.novaDisciplina('gbc011', 'matematica', 2)
sleep(2)
clienteAdministrativo2.novoAluno('123456', 'gabriel')
sleep(2)
clienteAdministrativo2.removeAluno('12345')
sleep(2)
clienteAdministrativo1_1.novoAluno('12345', 'rafael')
sleep(2)
clienteAdministrativo2.editaAluno('12345', 'luana')
sleep(2)
clienteAdministrativo2.novoAluno('1234567', 'lucas')
sleep(2)
clienteAdministrativo1_1.obtemTodosAlunos()
sleep(2)
clienteAdministrativo1.novaDisciplina('gbc012', 'fisica', 30)
sleep(2)
clienteAdministrativo2.obtemTodasDisciplinas()
sleep(2)
clienteAdministrativo1_1.obtemTodosProfessores()
sleep(2)
clienteAdministrativo1.obtemTodosAlunos()

# Sucesso clienteMatricula
clienteMatricula2.adicionaProfessor('gbc011', '09876')
sleep(2)
clienteMatricula1.adicionaProfessor('gbc012', '09876')
sleep(2)
clienteMatricula1_1.removeProfessor('gbc011', '09876')
sleep(2)
clienteMatricula1.adicionaAluno('gbc011', '12345')
sleep(2)
clienteMatricula1_1.adicionaAluno('gbc011', '123456')
sleep(2)
clienteMatricula1.removeProfessor('gbc011', '09876')
sleep(2)
clienteMatricula2.removeAluno('gbc011', '12345')
sleep(2)
clienteMatricula2.detalheDisciplina('gbc011')
sleep(2)
clienteMatricula1.obtemDisciplinasAluno('12345')
sleep(2)
clienteMatricula1_1.obtemDisciplinasProfessor('09876')

server_adm1.join()
server_adm2.join()
server_mat1.join()
server_mat2.join()
